AWSTemplateFormatVersion: "2010-09-09"
Description: Infrastructure du Site Vitrine - ProjetDeFous

Parameters:
  DomainName:
    Type: String
    Default: e5estiam.com
    Description: Nom de domaine principal géré par Route 53
  SubDomain:
    Type: String
    Default: site
    Description: Sous-domaine à configurer pour le site vitrine

Resources:
  ProjetDeFousSiteVitrineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${SubDomain}.${DomainName}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  ProjetDeFousSiteVitrineBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProjetDeFousSiteVitrineBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${ProjetDeFousSiteVitrineBucket.Arn}/*"

  ProjetDeFousHostedZone:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "${SubDomain}.${DomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !Sub "${ProjetDeFousSiteVitrineBucket.WebsiteURL}"

Outputs:
  ProjetDeFousSiteVitrineURL:
    Description: URL du site vitrine avec sous-domaine
    Value: !Sub "http://${SubDomain}.${DomainName}" 